spring:
  profiles:
    active:
    - dev

---

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jialei.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: Motorola123!
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
info:
  app.name: microserviceclound
  company.name: aaa
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jialei.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: Motorola123!
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
info:
  app.name: microserviceclound
  company.name: aaa
  build.artifactId: $project.artifactId$
  build.version: $project.version$

